apiVersion: v1
kind: Service
metadata:
  labels:
    name: nodejs-app
  name: nodejs-app
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 30001
    targetPort: 3000
    protocol: TCP
  selector:
    app: nodejs-app

